-- ClariFi Database Schema
-- Run these statements in Snowflake to set up the database

-- Database and Schema
CREATE DATABASE IF NOT EXISTS CLARIFI;
CREATE SCHEMA IF NOT EXISTS CLARIFI.CLAIMS;
USE SCHEMA CLARIFI.CLAIMS;

-- Image Repository for SPCS
CREATE IMAGE REPOSITORY IF NOT EXISTS CLARIFI.CLAIMS.CLARIFI_REPO;

-- Document Stage
CREATE STAGE IF NOT EXISTS CLARIFI.CLAIMS.CLAIM_DOCS_STAGE;

-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS POLICYHOLDERS (
    POLICYHOLDER_ID VARCHAR NOT NULL PRIMARY KEY,
    NAMA_LENGKAP VARCHAR NOT NULL,
    NO_KTP VARCHAR NOT NULL,
    TANGGAL_LAHIR DATE,
    JENIS_KELAMIN VARCHAR,
    ALAMAT VARCHAR,
    NO_TELEPON VARCHAR,
    EMAIL VARCHAR,
    TANGGAL_DAFTAR DATE DEFAULT CURRENT_DATE(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS POLICIES (
    POLICY_ID VARCHAR NOT NULL PRIMARY KEY,
    POLICYHOLDER_ID VARCHAR NOT NULL,
    PLAN_TYPE VARCHAR NOT NULL,
    COVERAGE_LIMIT NUMBER(15,2) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    EXCLUSIONS VARIANT,
    PREMI_BULANAN NUMBER(15,2),
    STATUS VARCHAR DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (POLICYHOLDER_ID) REFERENCES POLICYHOLDERS(POLICYHOLDER_ID)
);

CREATE TABLE IF NOT EXISTS CLAIM_SUBMISSIONS (
    CLAIM_ID VARCHAR NOT NULL PRIMARY KEY,
    POLICY_ID VARCHAR NOT NULL,
    PATIENT_ID VARCHAR NOT NULL,
    PATIENT_NAME VARCHAR NOT NULL,
    TANGGAL_KEJADIAN DATE NOT NULL,
    TANGGAL_PENGAJUAN DATE NOT NULL,
    JENIS_LAYANAN VARCHAR NOT NULL,
    NAMA_PROVIDER VARCHAR NOT NULL,
    DIAGNOSIS_AWAL VARCHAR,
    STATUS VARCHAR DEFAULT 'SUBMITTED',
    TOTAL_AMOUNT NUMBER(15,2) DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    APPROVED_AMOUNT FLOAT
);

CREATE TABLE IF NOT EXISTS CLAIM_LINE_ITEMS (
    LINE_ITEM_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID VARCHAR NOT NULL,
    ITEM_NO NUMBER NOT NULL,
    DESKRIPSI_TINDAKAN VARCHAR NOT NULL,
    KODE_TINDAKAN VARCHAR,
    JUMLAH_BIAYA NUMBER(15,2) NOT NULL,
    CATATAN_TAMBAHAN VARCHAR,
    FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_SUBMISSIONS(CLAIM_ID)
);

CREATE TABLE IF NOT EXISTS CLAIM_DOCUMENTS (
    DOCUMENT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID VARCHAR NOT NULL,
    DOCUMENT_TYPE VARCHAR NOT NULL,
    FILE_NAME VARCHAR NOT NULL,
    STAGE_PATH VARCHAR NOT NULL,
    UPLOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PARSE_STATUS VARCHAR(20) DEFAULT 'PENDING',
    PARSED_TEXT VARCHAR,
    DETECTED_DOC_TYPE VARCHAR(100),
    FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_SUBMISSIONS(CLAIM_ID)
);

CREATE TABLE IF NOT EXISTS ADJUDICATION_RESULTS (
    ADJUDICATION_ID VARCHAR DEFAULT UUID_STRING(),
    CLAIM_ID VARCHAR NOT NULL,
    FINAL_SCORE NUMBER(5,2),
    DECISION VARCHAR,
    DECISION_REASON VARCHAR,
    CRITERIA_BREAKDOWN VARIANT,
    ASSESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ASSESSED_BY VARCHAR DEFAULT 'SYSTEM'
);

CREATE TABLE IF NOT EXISTS ADJUDICATION_NOTES (
    NOTE_ID VARCHAR DEFAULT UUID_STRING(),
    CLAIM_ID VARCHAR NOT NULL,
    NOTE_TYPE VARCHAR,
    CONTENT VARCHAR NOT NULL,
    STATUS VARCHAR DEFAULT 'OPEN',
    CREATED_BY VARCHAR DEFAULT 'OFFICER',
    RESOLVED_BY VARCHAR,
    RESOLVED_AT TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CLAIM_STATUS_HISTORY (
    HISTORY_ID VARCHAR DEFAULT UUID_STRING(),
    CLAIM_ID VARCHAR NOT NULL,
    OLD_STATUS VARCHAR,
    NEW_STATUS VARCHAR NOT NULL,
    REASON VARCHAR,
    CHANGED_BY VARCHAR DEFAULT 'SYSTEM',
    CHANGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CLAIM_RULES (
    RULE_ID VARCHAR NOT NULL PRIMARY KEY,
    RULE_NAME VARCHAR NOT NULL,
    RULE_CATEGORY VARCHAR NOT NULL,
    CONDITION_EXPRESSION VARIANT,
    ACTION VARCHAR NOT NULL,
    PRIORITY NUMBER DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    DESCRIPTION VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FUZZY_AHP_WEIGHTS (
    CRITERIA_ID VARCHAR NOT NULL PRIMARY KEY,
    CRITERIA_NAME VARCHAR NOT NULL,
    WEIGHT NUMBER(5,4) NOT NULL,
    PARENT_CRITERIA_ID VARCHAR,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_GUIDELINE VARCHAR
);

CREATE TABLE IF NOT EXISTS EXTRACTED_FACTS (
    FACT_ID VARCHAR DEFAULT UUID_STRING(),
    CLAIM_ID VARCHAR NOT NULL,
    EXTRACTED_DATA VARIANT,
    SOURCE_DOCUMENTS VARIANT,
    EXTRACTION_METHOD VARCHAR,
    EXTRACTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS EXTRACTION_SUGGESTIONS (
    SUGGESTION_ID VARCHAR DEFAULT UUID_STRING(),
    CLAIM_ID VARCHAR NOT NULL,
    FIELD_NAME VARCHAR,
    FORM_VALUE VARCHAR,
    EXTRACTED_VALUE VARCHAR,
    SUGGESTION_TYPE VARCHAR,
    NOTE VARCHAR,
    OFFICER_DECISION VARCHAR,
    DECIDED_AT TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- SEED DATA: Fuzzy AHP Weights
-- ============================================================

INSERT INTO FUZZY_AHP_WEIGHTS (CRITERIA_ID, CRITERIA_NAME, WEIGHT, SOURCE_GUIDELINE) VALUES
('C1', 'Medical Necessity', 0.40, 'Primary criterion per clinical guidelines'),
('C2', 'Policy Compliance', 0.25, 'Contract adherence check'),
('C3', 'Documentation Completeness', 0.20, 'Supporting document verification'),
('C4', 'Cost Reasonableness', 0.15, 'Market rate comparison');

-- ============================================================
-- AUTOMATION: Stream + Task for auto-adjudication
-- ============================================================

CREATE STREAM IF NOT EXISTS NEW_CLAIMS_STREAM
    ON TABLE CLAIM_SUBMISSIONS
    APPEND_ONLY = TRUE;

-- (Stored procedure and Task creation — see deploy/spcs_deploy.sql)

-- ============================================================
-- CORTEX SEARCH: Similar Claims
-- ============================================================

CREATE OR REPLACE VIEW CLAIMS_SEARCH_VIEW AS
SELECT
    cs.claim_id, cs.patient_name, cs.diagnosis_awal, cs.jenis_layanan,
    cs.nama_provider, cs.total_amount, cs.status,
    COALESCE(ar.final_score, 0) as final_score,
    COALESCE(ar.decision, 'Pending') as decision,
    cs.diagnosis_awal || ' | ' || cs.jenis_layanan || ' | ' || cs.nama_provider || ' | ' ||
    COALESCE(ar.decision_reason, '') || ' | ' || COALESCE(li_agg.procedures_text, '') AS search_text
FROM CLAIM_SUBMISSIONS cs
LEFT JOIN (
    SELECT claim_id, MAX(final_score) as final_score, MAX(decision) as decision, MAX(decision_reason) as decision_reason
    FROM ADJUDICATION_RESULTS GROUP BY claim_id
) ar ON cs.claim_id = ar.claim_id
LEFT JOIN (
    SELECT claim_id, LISTAGG(deskripsi_tindakan, '; ') WITHIN GROUP (ORDER BY item_no) as procedures_text
    FROM CLAIM_LINE_ITEMS GROUP BY claim_id
) li_agg ON cs.claim_id = li_agg.claim_id;

-- CREATE CORTEX SEARCH SERVICE SIMILAR_CLAIMS_SEARCH
--   ON search_text
--   ATTRIBUTES claim_id, patient_name, diagnosis_awal, jenis_layanan, total_amount, status, final_score, decision
--   WAREHOUSE = COMPUTE_WH
--   TARGET_LAG = '1 hour'
--   AS SELECT * FROM CLAIMS_SEARCH_VIEW;
